In [203]:
import pandas as pd
import requests
from datetime import datetime
from datetime import timezone

In [222]:
class CryptoCompare:
    
    def timeStamp(self,date):
        timestamp = date.replace(tzinfo=timezone.utc).timestamp()
        return int(timestamp)
    
    def getData(self,fsym,tsym,start_time,end_time,e):
        http = "https://min-api.cryptocompare.com/data/v2/histohour?fsym="+fsym+"&tsym="+tsym+"&limit=1&toTs="+end_time+"&e="+ e
        r = requests.get(http)
        print(r)
        data = r.json()
        value = data['Data']['Data']
        df = pd.DataFrame(value, columns=['close','high', 'low','open','volumefrom','volumeto','time'])
        end_time = str(data['Data']['TimeFrom'])
        while (data['Data']['TimeFrom'] > int(start_time)):
            http = "https://min-api.cryptocompare.com/data/v2/histohour?fsym="+fsym+"&tsym="+tsym+"&limit=2000&toTs="+end_time+"&e="+ e
            r = requests.get(http)
            data = r.json()
            value = data['Data']['Data']
            df1 = pd.DataFrame(value, columns=['close','high', 'low','open','volumefrom','volumeto','time'])
            df = df1.append(df)
            end_time = str(data['Data']['TimeFrom'])
        df = df.reset_index(drop=True)
        df = df[df['time']>=int(start_time)]
        df = df.reset_index(drop=True)
        df['time'] = pd.to_datetime(df['time'],unit='s')
        df = df.rename(columns={"volumefrom": "volume", "volumeto": "baseVolume","time":"datetime"})
        df = df.drop_duplicates()
        df.to_csv('data.csv',index=False)
        return df

In [223]:
a = CryptoCompare()
print(a.timeStamp(datetime(2020,4,1)))
print(a.timeStamp(datetime(2017,4,1)))
a.getData('BTC','USDT','1491004800','1585699200','binance')

1585699200
1491004800
<Response [200]>

,close,high,low,open,volume,baseVolume,datetime
0,0.00,0.00,0.00,0.00,0.00,0.00,2017-04-01 00:00:00
1,0.00,0.00,0.00,0.00,0.00,0.00,2017-04-01 01:00:00
2,0.00,0.00,0.00,0.00,0.00,0.00,2017-04-01 02:00:00
3,0.00,0.00,0.00,0.00,0.00,0.00,2017-04-01 03:00:00
4,0.00,0.00,0.00,0.00,0.00,0.00,2017-04-01 04:00:00
5,0.00,0.00,0.00,0.00,0.00,0.00,2017-04-01 05:00:00
6,0.00,0.00,0.00,0.00,0.00,0.00,2017-04-01 06:00:00
7,0.00,0.00,0.00,0.00,0.00,0.00,2017-04-01 07:00:00
8,0.00,0.00,0.00,0.00,0.00,0.00,2017-04-01 08:00:00
9,0.00,0.00,0.00,0.00,0.00,0.00,2017-04-01 09:00:00
10,0.00,0.00,0.00,0.00,0.00,0.00,2017-04-01 10:00:00
11,0.00,0.00,0.00,0.00,0.00,0.00,2017-04-01 11:00:00
12,0.00,0.00,0.00,0.00,0.00,0.00,2017-04-01 12:00:00
13,0.00,0.00,0.00,0.00,0.00,0.00,2017-04-01 13:00:00
14,0.00,0.00,0.00,0.00,0.00,0.00,2017-04-01 14:00:00
15,0.00,0.00,0.00,0.00,0.00,0.00,2017-04-01 15:00:00
16,0.00,0.00,0.00,0.00,0.00,0.00,2017-04-01 16:00:00
17,0.00,0.00,0.00,0.00,0.00,0.00,2017-04-01 17:00:00
18,0.00,0.00,0.00,0.00,0.00,0.00,2017-04-01 18:00:00
19,0.00,0.00,0.00,0.00,0.00,0.00,2017-04-01 19:00:00
20,0.00,0.00,0.00,0.00,0.00,0.00,2017-04-01 20:00:00
21,0.00,0.00,0.00,0.00,0.00,0.00,2017-04-01 21:00:00
22,0.00,0.00,0.00,0.00,0.00,0.00,2017-04-01 22:00:00
23,0.00,0.00,0.00,0.00,0.00,0.00,2017-04-01 23:00:00
24,0.00,0.00,0.00,0.00,0.00,0.00,2017-04-02 00:00:00
25,0.00,0.00,0.00,0.00,0.00,0.00,2017-04-02 01:00:00
26,0.00,0.00,0.00,0.00,0.00,0.00,2017-04-02 02:00:00
27,0.00,0.00,0.00,0.00,0.00,0.00,2017-04-02 03:00:00
28,0.00,0.00,0.00,0.00,0.00,0.00,2017-04-02 04:00:00
29,0.00,0.00,0.00,0.00,0.00,0.00,2017-04-02 05:00:00
...,...,...,...,...,...,...,...
26288,6366.74,6402.41,6346.18,6363.01,2451.64,15609364.17,2020-03-30 19:00:00
26289,6463.30,6500.00,6363.78,6366.74,7033.57,45313451.20,2020-03-30 20:00:00
26290,6528.47,6564.33,6462.37,6463.30,6444.10,41972972.45,2020-03-30 21:00:00
26291,6458.00,6599.00,6440.29,6528.47,6595.56,43037093.33,2020-03-30 22:00:00
26292,6394.38,6483.54,6375.00,6458.00,5298.19,34085895.72,2020-03-30 23:00:00
26293,6439.55,6469.28,6380.00,6394.38,3456.74,22258381.62,2020-03-31 00:00:00
26294,6514.07,6515.00,6439.55,6439.55,2564.81,16621482.91,2020-03-31 01:00:00
26295,6449.66,6523.23,6445.00,6514.07,2638.25,17108477.85,2020-03-31 02:00:00
26296,6439.47,6480.00,6408.00,6449.66,3522.06,22691104.85,2020-03-31 03:00:00
26297,6398.93,6465.00,6378.00,6439.47,3855.14,24729796.97,2020-03-31 04:00:00
26298,6415.60,6453.00,6380.96,6398.93,2207.25,14154300.63,2020-03-31 05:00:00
26299,6471.56,6471.56,6390.00,6415.60,3093.53,19908119.92,2020-03-31 06:00:00
26300,6445.09,6473.68,6425.48,6471.56,2008.27,12946172.84,2020-03-31 07:00:00
26301,6493.93,6505.50,6441.71,6445.09,3412.17,22099117.38,2020-03-31 08:00:00
26302,6440.04,6499.00,6425.00,6493.93,3365.66,21756849.30,2020-03-31 09:00:00
26303,6431.32,6441.30,6404.00,6440.04,2779.52,17849949.14,2020-03-31 10:00:00
26304,6387.19,6432.29,6330.01,6431.32,5307.47,33851325.81,2020-03-31 11:00:00
26305,6447.37,6461.95,6321.40,6387.19,4797.74,30648571.81,2020-03-31 12:00:00
26306,6418.00,6481.28,6400.07,6447.37,4091.87,26358461.37,2020-03-31 13:00:00
26307,6452.04,6484.95,6415.15,6418.00,3234.98,20883874.64,2020-03-31 14:00:00
26308,6454.12,6500.00,6424.00,6452.04,3921.33,25343803.86,2020-03-31 15:00:00
26309,6427.59,6469.94,6414.05,6454.12,2812.79,18120887.14,2020-03-31 16:00:00
26310,6452.79,6459.00,6401.00,6427.59,2362.33,15200058.27,2020-03-31 17:00:00
26311,6462.37,6486.60,6444.82,6452.79,2326.75,15038936.47,2020-03-31 18:00:00
26312,6463.47,6475.00,6430.32,6462.37,2485.86,16047293.92,2020-03-31 19:00:00
26313,6467.50,6494.90,6447.75,6463.47,2503.51,16207519.69,2020-03-31 20:00:00
26314,6442.61,6485.00,6420.00,6467.50,2112.04,13622726.48,2020-03-31 21:00:00
26315,6431.55,6448.00,6420.64,6442.61,1197.65,7707041.79,2020-03-31 22:00:00
26316,6410.44,6440.99,6386.89,6431.55,2279.88,14626241.96,2020-03-31 23:00:00
26318,6305.12,6426.52,6239.34,6410.44,9061.28,57230360.58,2020-04-01 00:00:00